GET http://localhost:5000/users

###
GET http://localhost:5000/users/8

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "nilam",
    "email": "nilam@gmail.com",
    "gender": "female"
}